public class CaseResult {
	@AuraEnabled public Boolean attachments;
    @AuraEnabled public String reference;
    @AuraEnabled public String modifiedDate;
    @AuraEnabled public String createdDate;
    @AuraEnabled public String lob;
    @AuraEnabled public String contactType;
    @AuraEnabled public String mileage;
    @AuraEnabled public String status;
    @AuraEnabled public String link;
    @AuraEnabled public boolean serviceUnavailable=false;
}