@isTest
public class CaseResultTest {
    public testmethod static void CaseResultTestMethod(){
        CaseResult CaseRslt= new CaseResult();
         CaseRslt.attachments=true;
         CaseRslt.reference='xyz';
         CaseRslt.modifiedDate='june';
         CaseRslt.createdDate='jan';
         CaseRslt.lob='gjhg';
         CaseRslt.contactType='abc';
         CaseRslt.mileage='hgfgd';
         CaseRslt.status='open';
         CaseRslt.link='svdhgsaf';
         CaseRslt.serviceUnavailable=false;

        
        
    }
}